
# Numpy Libaray                     
                                                                                         # code written by
                                                                                            - rashiddaha

In [ ]:
!pip install numpy

In [1]:
import numpy as np


In [2]:
#list 
list1=[1,2,3,4,5]

In [3]:
list1

[1, 2, 3, 4, 5]

In [4]:
list2=[6,7,8,9,10]

In [5]:
#uasig numpy creating mutidimensional array 
add= np.array([list1,list2])

In [6]:
add

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
add.shape

(2, 5)

In [9]:
type(add)


numpy.ndarray

In [14]:
#Re-shaping the structure of 2d array  into 2 columns and 5 arrays .
reshape_now=add.reshape(5,2)

In [15]:
reshape_now

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [18]:
#accessing the fifth Eelement
add[1]
reshape_now[4]

array([ 9, 10])

In [24]:
reshape_now[:,:]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [31]:
reshape_now[:]

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [45]:
# creating a new list using numpy
new_list1=np.arange(0,10)

In [48]:
new_list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# creating a new list using numpy
new_list2=np.arange(0,10, step=3)

In [47]:
new_list2

array([0, 3, 6, 9])

In [50]:
#it will repaete all elemsts from the selection element to onwords .
new_list2[2:]=40

In [51]:
new_list2

array([ 0,  3, 40, 40])

In [54]:
# generating random values in specific range
np.linspace(1,5,30)

array([1.        , 1.13793103, 1.27586207, 1.4137931 , 1.55172414,
       1.68965517, 1.82758621, 1.96551724, 2.10344828, 2.24137931,
       2.37931034, 2.51724138, 2.65517241, 2.79310345, 2.93103448,
       3.06896552, 3.20689655, 3.34482759, 3.48275862, 3.62068966,
       3.75862069, 3.89655172, 4.03448276, 4.17241379, 4.31034483,
       4.44827586, 4.5862069 , 4.72413793, 4.86206897, 5.        ])

In [56]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [61]:
#generating random 2 rows of 5 columns
np.random.randn(2,5)

array([[ 0.10091178,  0.28895549, -0.08519105, -0.16772105, -0.86753238],
       [ 1.63100935, -0.85054508, -0.62628044, -0.43486719,  1.58542619]])